SELECT
T1.MODEL_SUFFIX,
COUNT(T1.ID) AS ITEM_COUNT

FROM MODEL T1

JOIN MODEL_ITEMS T2
ON T1.ID = T2.MODEL_ID

JOIN ORGANISATION T3
ON T3.ID = T1.ORGANISATION_ID

WHERE T1.CREATED_AT >= GETDATE()-120

AND T2.PART_NUMBER LIKE 'EAX%'
AND T3.ORG_CODE IN ('NW1','NW9')

GROUP BY 
T1.MODEL_SUFFIX, 
T2.PART_NUMBER, 
T3.ORG_CODE

ORDER BY 
ITEM_COUNT DESC